export const ownerDetail = {
  name: 'Karthik Sivakumar',
  email: 'karthik@withpractice.ai',
  phone: '+1 (650) 555-5555',
  address: '123 Main St, Anytown, USA',
  city: 'Anytown',
  state: 'CA',
  zip: '12345',
  country: 'USA',
  website: 'https://www.practiceai.com',
  linkedin: 'https://www.linkedin.com/in/karthik-sivakumar',
  twitter: 'https://twitter.com/karthik-sivakumar',
  github: 'https://github.com/karthik-sivakumar',
  instagram: 'https://www.instagram.com/karthik-sivakumar',
  facebook: 'https://www.facebook.com/karthik-sivakumar',
  calendlyLink: 'https://calendly.com/karthik-withpractice',
};
